version: "3.9"
services:
  m1:
    image: db
    build:
      dockerfile: MasterDockerfile
    ports:
      - "8000:8080"

  m1s1:
    image: db
    ports:
      - "8001:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m1

  m1s2:
    image: db
    ports:
      - "8002:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m1

  m1s3:
    image: db
    ports:
      - "8003:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m1

  m2:
    image: db
    build:
      dockerfile: MasterDockerfile
    ports:
      - "8010:8080"

  m2s1:
    image: db
    ports:
      - "8011:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m2

  m2s2:
    image: db
    ports:
      - "8012:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m2

  m2s3:
    image: db
    ports:
      - "8013:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m2
  m3:
    image: db
    build:
      dockerfile: MasterDockerfile
    ports:
      - "8020:8080"

  m3s1:
    image: db
    ports:
      - "8021:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m3

  m3s2:
    image: db
    ports:
      - "8022:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m3

  m3s3:
    image: db
    ports:
      - "8023:8080"
    build:
      dockerfile: SlaveDockerfile
    depends_on:
      - m3
